<%
  elasticsearch_hosts = nil
  elasticsearch_port = nil
  if_link("elasticsearch") { |elasticsearch_link|
    elasticsearch_hosts = elasticsearch_link.instances.map { |instance| instance.address }
    elasticsearch_port = elasticsearch_link.p("elasticsearch.port")
  }
  unless elasticsearch_hosts
    elasticsearch_hosts = p("curator.elasticsearch.hosts")
  end
  unless elasticsearch_port
    elasticsearch_port = p("curator.elasticsearch.port")
  end
%>
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: <%= elasticsearch_hosts %>
  port: p("curator.elasticsearch.port")
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
