<%
  elasticsearch_hosts = nil
  if_link("elasticsearch") { |elasticsearch_link|
    elasticsearch_hosts = elasticsearch_link.instances.map { |instance| instance.address }
  }
  unless elasticsearch_hosts
    elasticsearch_hosts = p("curator.elasticsearch.hosts")
  end
%>
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: <%= elasticsearch_hosts %>
  port: <%= p("curator.elasticsearch.port") %>
  url_prefix: <%= p("curator.elasticsearch.url_prefix") %>
  use_ssl: <%= p("curator.elasticsearch.use_ssl") %>
  certificate: <%= p("curator.elasticsearch.certificate") %>
  client_cert: <%= p("curator.elasticsearch.client_cert") %>
  client_key: <%= p("curator.elasticsearch.client_key") %>
  ssl_no_validate: <%= p("curator.elasticsearch.ssl_no_validate") %>
  http_auth: <%= p("curator.elasticsearch.http_auth") %>
  timeout: <%= p("curator.elasticsearch.timeout") %>
  master_only: <%= p("curator.elasticsearch.master_only") %>

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
